services:
  - docker

env:
  global:
    - DOCKER_ACCOUNT=sogis
    - DOCKER_REPO=realty-utility-service

branches:
  only:
    - master

script:
  - mvn -B package
  - docker build -t $DOCKER_ACCOUNT/$DOCKER_REPO:latest -t $DOCKER_ACCOUNT/$DOCKER_REPO:$TRAVIS_BUILD_NUMBER -f src/main/docker/Dockerfile.jvm

deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin && docker push $DOCKER_ACCOUNT/$DOCKER_REPO
  on:
    branch: master

cache:
  directories:
  - $HOME/.m2
